### ISSUE TITLE
Can not save image

### ISSUE THREAD

**Issue by sunjianan9900** [Samoy/image_save#1]
Android
`await ImageSave.saveImage("gif", Uint8List.fromList(_gif));
`
Error:
java.io.FileNotFoundException: /storage/emulated/0/测试APP/IMAGE_1571584085719.gif (No such file or directory)

the path not looks like not album path...
App name: "测试APP"

**Comment by Samoy** [comment]
Android的文件储存在该App名字路径下，iOS保存在相册。

**Comment by sunjianan9900** [comment]
知道了～谢谢
