### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method saveImage on channel image_save

### ISSUE THREAD

**Issue by 54lianxi** [Samoy/image_save#2]
this is my problem,I am using your example on the pub
E/flutter ( 8461): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method saveImage on channel image_save)
E/flutter ( 8461): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 8461): <asynchronous suspension>
E/flutter ( 8461): #1      ImageSave.saveImage (package:image_save/image_save.dart:10:40)
E/flutter ( 8461): #2      _MyAppState._saveImage (package:flutterapp/main.dart:33:23)
E/flutter ( 8461): <asynchronous suspension>
E/flutter ( 8461): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)

**Comment by Samoy** [comment]
Example updated.
