### ISSUE TITLE
为啥我用的时候报不兼容AndroidX

### ISSUE THREAD

**Issue by Sansuihe** [Samoy/image_save#3]
D:\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\image_save-1.1.3\android\src\main\java\com\samoy\image_save\ImageSavePlugin.java:9: ����: �����android.support.annotation������
import android.support.annotation.NonNull;
                                 ^
D:\SDK\flutter\.pub-cache\hosted\pub.dartlang.org\image_save-1.1.3\android\src\main\java\com\samoy\image_save\ImageSavePlugin.java:41: ����: �Ҳ�������
  public void onMethodCall(MethodCall call,@NonNull Result result) {
                                            ^
  ����:   �� NonNull
  λ��: �� ImageSavePlugin
2 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_save:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Samoy** [comment]
已修复，请使用1.1.3+1版本
