### ISSUE TITLE
File path adapt for new Android version

### ISSUE THREAD

**Issue by AlexVincent525** [Samoy/image_save#5]
Currently image file will be saved at `/stroage/emulated/0/{album_name}/IMAGE_$timestamp.$extension`. But according to new rules about the storage, the file might be saved at `/storage/emulated/0/Android/data/xxx.xxxxxx.xx/files/{album_name}/IMAGE_$timestamp.$extension`.

Also, is there possible to expose `image name` parameter for custom image name? e.g. I want the image filename as same as it was before.

Sorry, 没注意到是国人^_^
可否以新方式存储在对应的文件夹中？另外是否能暴露设置文件名的参数？

**Comment by Samoy** [comment]
好的，我会更新版本

**Comment by Samoy** [comment]
> Currently image file will be saved at `/stroage/emulated/0/{album_name}/IMAGE_$timestamp.$extension`. But according to new rules about the storage, the file might be saved at `/storage/emulated/0/Android/data/xxx.xxxxxx.xx/files/{album_name}/IMAGE_$timestamp.$extension`.
> 
> Also, is there possible to expose `image name` parameter for custom image name? e.g. I want the image filename as same as it was before.
> 
> Sorry, 没注意到是国人^_^
> 可否以新方式存储在对应的文件夹中？另外是否能暴露设置文件名的参数？

现在可以用`2.1.0`版本中的`saveImageToSandbox`方法。

**Comment by AlexVincent525** [comment]
OK，`saveImage`是否也可以支持定义文件名？

**Comment by Samoy** [comment]
> OK，`saveImage`是否也可以支持定义文件名？

没有多大意义，在iOS上，储存在相册里的图片不支持自定义名字，不暴露设置文件名的参数是为了保持两端统一。
