### ISSUE TITLE
保存源生组件时出错

### ISSUE THREAD

**Issue by CoderHln** [Samoy/image_save#6]
[VERBOSE-2:platform_view_layer.cc(22)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(39)] Trying to embed a platform view but the PaintContext does not support embedding

**Comment by CoderHln** [comment]
import 'package:flutter/services.dart';
导入这个就可以了。

**Comment by CoderHln** [comment]
[VERBOSE-2:platform_view_layer.cc(22)] Trying to embed a platform view but the PrerollContext does not support embedding
[VERBOSE-2:platform_view_layer.cc(39)] Trying to embed a platform view but the PaintContext does not support embedding


在保存组件的时候，如果组件是platform_view，例如webView，就会报这个，建议在iOS项目下，info.plist中加入 <key>io.flutter.embedded_views_preview</key><true/>  即可，应该是可以保存到源生的组件。

**Comment by CoderHln** [comment]
<key>io.flutter.embedded_views_preview</key>
    <true/>

**Comment by Samoy** [comment]
> 在保存组件的时候，如果组件是platform_view，例如webView，就会报这个，建议在iOS项目下，info.plist中加入 `<key>io.flutter.embedded_views_preview</key><true/>` 即可，应该是可以保存到源生的组件。

这个组件是用来保存图片的，你的意思是从webview里面保存图片吗？

**Comment by CoderHln** [comment]
> > 在保存组件的时候，如果组件是platform_view，例如webView，就会报这个，建议在iOS项目下，info.plist中加入 `<key>io.flutter.embedded_views_preview</key><true/>` 即可，应该是可以保存到源生的组件。
> 
> 这个组件是用来保存图片的，你的意思是从webview里面保存图片吗？

是我理解错了，我是把widget转换成图片然后保存，但是在转源生组件的时候出现问题了，跟本库保存图片功能没有关系的。目前遇到个问题就是，flutter for web 保存图片的时候会报
matrix4[0] == window.devicePixelRatio &&
           matrix4[5] == window.devicePixelRatio
is not true
是不支持flutter for web吗？

**Comment by Samoy** [comment]
> > > 在保存组件的时候，如果组件是platform_view，例如webView，就会报这个，建议在iOS项目下，info.plist中加入 `<key>io.flutter.embedded_views_preview</key><true/>` 即可，应该是可以保存到源生的组件。
> > 
> > 
> > 这个组件是用来保存图片的，你的意思是从webview里面保存图片吗？
> 
> 是我理解错了，我是把widget转换成图片然后保存，但是在转源生组件的时候出现问题了，跟本库保存图片功能没有关系的。目前遇到个问题就是，flutter for web 保存图片的时候会报
> matrix4[0] == window.devicePixelRatio &&
> matrix4[5] == window.devicePixelRatio
> is not true
> 是不支持flutter for web吗？

暂不支持，后续我会添加

**Comment by Samoy** [comment]
> > > 在保存组件的时候，如果组件是platform_view，例如webView，就会报这个，建议在iOS项目下，info.plist中加入 `<key>io.flutter.embedded_views_preview</key><true/>` 即可，应该是可以保存到源生的组件。
> > 
> > 
> > 这个组件是用来保存图片的，你的意思是从webview里面保存图片吗？
> 
> 是我理解错了，我是把widget转换成图片然后保存，但是在转源生组件的时候出现问题了，跟本库保存图片功能没有关系的。目前遇到个问题就是，flutter for web 保存图片的时候会报
> matrix4[0] == window.devicePixelRatio &&
> matrix4[5] == window.devicePixelRatio
> is not true
> 是不支持flutter for web吗？

查了相关资料，浏览器不允许通过js操作下载文件，而且一般现在浏览器应该会自带的有保存图片的功能吧，所以现在我无法实现该功能，若你有更好的想法，可以回复该issue.
