### ISSUE TITLE
Need to name the image file before saving it and get the path to the image

### ISSUE THREAD

**Issue by nekoto-kun** [Samoy/image_save#8]
This plugin works so well, but it lacks feature to rename the saved image file when using the method ```saveImage()```, though it's quite helpful with ```albumName``` to name the folder in storage before saving the image file. Please add this feature, thanks. 🤞

**Comment by nekoto-kun** [comment]
One more to add is I want to get the full path to the saved image, so I can check whether the image is already saved in the desired path or not.

**Comment by Samoy** [comment]
Sorry, on iOS, the image saved to the album **do not support** naming and it is **not recommended** to obtain the path. In order to maintain the consistency of the two platforms, this feature is not considered for now. If you have a better idea, please reply to this issue. Thank you.
